// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistency.Data;

namespace Persistency.Migrations
{
    [DbContext(typeof(VitaeContext))]
    [Migration("20200524181941_v.1.0.0")]
    partial class v100
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.Poco.About", b =>
                {
                    b.Property<Guid>("AboutID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcademicTitle")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CurriculumID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CurriculumLanguageLanguageID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Photo")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Slogan")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<Guid?>("VfileID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AboutID");

                    b.HasIndex("CurriculumID");

                    b.HasIndex("CurriculumLanguageLanguageID");

                    b.HasIndex("VfileID");

                    b.ToTable("About");
                });

            modelBuilder.Entity("Model.Poco.Abroad", b =>
                {
                    b.Property<Guid>("AbroadID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<Guid>("CountryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CurriculumID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CurriculumLanguageLanguageID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<DateTime?>("End")
                        .HasColumnType("datetime2");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.HasKey("AbroadID");

                    b.HasIndex("CountryID");

                    b.HasIndex("CurriculumID");

                    b.HasIndex("CurriculumLanguageLanguageID");

                    b.ToTable("Abroad");
                });

            modelBuilder.Entity("Model.Poco.Award", b =>
                {
                    b.Property<Guid>("AwardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AwardedFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("AwardedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CurriculumID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CurriculumLanguageLanguageID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("AwardID");

                    b.HasIndex("CurriculumID");

                    b.HasIndex("CurriculumLanguageLanguageID");

                    b.ToTable("Award");
                });

            modelBuilder.Entity("Model.Poco.Certificate", b =>
                {
                    b.Property<Guid>("CertificateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CurriculumID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CurriculumLanguageLanguageID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<DateTime?>("ExpiresOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IssuedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("CertificateID");

                    b.HasIndex("CurriculumID");

                    b.HasIndex("CurriculumLanguageLanguageID");

                    b.ToTable("Certificate");
                });

            modelBuilder.Entity("Model.Poco.Child", b =>
                {
                    b.Property<Guid>("ChildID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid?>("PersonalDetailID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ChildID");

                    b.HasIndex("PersonalDetailID");

                    b.ToTable("Child");
                });

            modelBuilder.Entity("Model.Poco.Country", b =>
                {
                    b.Property<Guid>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("Iso3")
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name_de")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name_es")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name_fr")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name_it")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int?>("NumCode")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("PhoneCode")
                        .HasColumnType("int");

                    b.HasKey("CountryID");

                    b.HasIndex("CountryCode")
                        .IsUnique()
                        .HasFilter("[CountryCode] IS NOT NULL");

                    b.HasIndex("Name");

                    b.HasIndex("Order");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("Model.Poco.Course", b =>
                {
                    b.Property<Guid>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<Guid>("CountryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CurriculumID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CurriculumLanguageLanguageID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<DateTime?>("End")
                        .HasColumnType("datetime2");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("CourseID");

                    b.HasIndex("CountryID");

                    b.HasIndex("CurriculumID");

                    b.HasIndex("CurriculumLanguageLanguageID");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("Model.Poco.Curriculum", b =>
                {
                    b.Property<Guid>("CurriculumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LanguageID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CurriculumID");

                    b.HasIndex("LanguageID");

                    b.ToTable("Curriculum");
                });

            modelBuilder.Entity("Model.Poco.CurriculumLanguage", b =>
                {
                    b.Property<Guid>("CurriculumID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LanguageID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("CurriculumID", "LanguageID");

                    b.HasIndex("CurriculumID");

                    b.HasIndex("LanguageID");

                    b.ToTable("CurriculumLanguage");
                });

            modelBuilder.Entity("Model.Poco.Education", b =>
                {
                    b.Property<Guid>("EducationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<Guid>("CountryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CurriculumID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CurriculumLanguageLanguageID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<DateTime?>("End")
                        .HasColumnType("datetime2");

                    b.Property<float?>("Grade")
                        .HasColumnType("real");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("EducationID");

                    b.HasIndex("CountryID");

                    b.HasIndex("CurriculumID");

                    b.HasIndex("CurriculumLanguageLanguageID");

                    b.ToTable("Education");
                });

            modelBuilder.Entity("Model.Poco.Experience", b =>
                {
                    b.Property<Guid>("ExperienceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("CompanyDescription")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<Guid>("CountryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CurriculumID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CurriculumLanguageLanguageID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<DateTime?>("End")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HierarchyLevelID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IndustryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.HasKey("ExperienceID");

                    b.HasIndex("CountryID");

                    b.HasIndex("CurriculumID");

                    b.HasIndex("CurriculumLanguageLanguageID");

                    b.HasIndex("HierarchyLevelID");

                    b.HasIndex("IndustryID");

                    b.ToTable("Experience");
                });

            modelBuilder.Entity("Model.Poco.HierarchyLevel", b =>
                {
                    b.Property<Guid>("HierarchyLevelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HierarchyLevelCode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name_de")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name_es")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name_fr")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name_it")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("HierarchyLevelID");

                    b.HasIndex("HierarchyLevelCode")
                        .IsUnique();

                    b.ToTable("HierarchyLevel");
                });

            modelBuilder.Entity("Model.Poco.Industry", b =>
                {
                    b.Property<Guid>("IndustryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IndustryCode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name_de")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name_es")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name_fr")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name_it")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("IndustryID");

                    b.HasIndex("IndustryCode")
                        .IsUnique();

                    b.ToTable("Industry");
                });

            modelBuilder.Entity("Model.Poco.Interest", b =>
                {
                    b.Property<Guid>("InterestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Association")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CurriculumID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CurriculumLanguageLanguageID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("InterestName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("InterestID");

                    b.HasIndex("CurriculumID");

                    b.HasIndex("CurriculumLanguageLanguageID");

                    b.ToTable("Interest");
                });

            modelBuilder.Entity("Model.Poco.Language", b =>
                {
                    b.Property<Guid>("LanguageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name_de")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name_es")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name_fr")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name_it")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("LanguageID");

                    b.HasIndex("LanguageCode")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Order");

                    b.ToTable("Language");
                });

            modelBuilder.Entity("Model.Poco.LanguageSkill", b =>
                {
                    b.Property<Guid>("LanguageSkillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CurriculumID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CurriculumLanguageLanguageID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<float>("Rate")
                        .HasColumnType("real");

                    b.Property<Guid?>("SpokenLanguageID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LanguageSkillID");

                    b.HasIndex("CurriculumID");

                    b.HasIndex("CurriculumLanguageLanguageID");

                    b.HasIndex("SpokenLanguageID");

                    b.ToTable("LanguageSkill");
                });

            modelBuilder.Entity("Model.Poco.LogActivity", b =>
                {
                    b.Property<long>("LogActivityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("CurriculumID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<int>("LogArea")
                        .HasColumnType("int");

                    b.Property<int>("LogLevel")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("UserLanguage")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.HasKey("LogActivityID");

                    b.HasIndex("CurriculumID");

                    b.HasIndex("Timestamp");

                    b.ToTable("LogActivity");
                });

            modelBuilder.Entity("Model.Poco.LogPublication", b =>
                {
                    b.Property<long>("LogPublicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("CurriculumID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<int>("LogArea")
                        .HasColumnType("int");

                    b.Property<int>("LogLevel")
                        .HasColumnType("int");

                    b.Property<Guid>("PublicationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("UserLanguage")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.HasKey("LogPublicationID");

                    b.HasIndex("CurriculumID");

                    b.HasIndex("PublicationID");

                    b.HasIndex("Timestamp");

                    b.ToTable("LogPublication");
                });

            modelBuilder.Entity("Model.Poco.MaritalStatus", b =>
                {
                    b.Property<Guid>("MaritalStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaritalStatusCode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name_de")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name_es")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name_fr")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name_it")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("MaritalStatusID");

                    b.HasIndex("MaritalStatusCode")
                        .IsUnique();

                    b.ToTable("MaritalStatus");
                });

            modelBuilder.Entity("Model.Poco.Month", b =>
                {
                    b.Property<Guid>("MonthID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MonthCode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name_de")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name_es")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name_fr")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name_it")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("MonthID");

                    b.HasIndex("MonthCode")
                        .IsUnique();

                    b.ToTable("Month");
                });

            modelBuilder.Entity("Model.Poco.PersonCountry", b =>
                {
                    b.Property<Guid>("PersonalDetailID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("PersonalDetailID", "CountryID");

                    b.HasIndex("CountryID");

                    b.ToTable("PersonCountry");
                });

            modelBuilder.Entity("Model.Poco.PersonalDetail", b =>
                {
                    b.Property<Guid>("PersonalDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Citizenship")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<Guid?>("CountryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CurriculumID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CurriculumLanguageLanguageID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<Guid?>("MaritalStatusID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)")
                        .HasMaxLength(16);

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("PhonePrefix")
                        .IsRequired()
                        .HasColumnType("nvarchar(6)")
                        .HasMaxLength(6);

                    b.Property<Guid?>("SpokenLanguageID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("StreetNo")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("PersonalDetailID");

                    b.HasIndex("CountryID");

                    b.HasIndex("CurriculumID");

                    b.HasIndex("CurriculumLanguageLanguageID");

                    b.HasIndex("MaritalStatusID");

                    b.HasIndex("SpokenLanguageID");

                    b.ToTable("PersonalDetail");
                });

            modelBuilder.Entity("Model.Poco.Publication", b =>
                {
                    b.Property<Guid>("PublicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Anonymize")
                        .HasColumnType("bit");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CurriculumID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CurriculumLanguageLanguageID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<Guid>("PublicationIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Secure")
                        .HasColumnType("bit");

                    b.HasKey("PublicationID");

                    b.HasIndex("CurriculumID");

                    b.HasIndex("CurriculumLanguageLanguageID");

                    b.HasIndex("PublicationIdentifier")
                        .IsUnique();

                    b.ToTable("Publication");
                });

            modelBuilder.Entity("Model.Poco.Reference", b =>
                {
                    b.Property<Guid>("ReferenceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<Guid?>("CountryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CurriculumID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CurriculumLanguageLanguageID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<bool>("Hide")
                        .HasColumnType("bit");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)")
                        .HasMaxLength(16);

                    b.Property<string>("PhonePrefix")
                        .IsRequired()
                        .HasColumnType("nvarchar(6)")
                        .HasMaxLength(6);

                    b.HasKey("ReferenceID");

                    b.HasIndex("CountryID");

                    b.HasIndex("CurriculumID");

                    b.HasIndex("CurriculumLanguageLanguageID");

                    b.ToTable("Reference");
                });

            modelBuilder.Entity("Model.Poco.Skill", b =>
                {
                    b.Property<Guid>("SkillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CurriculumID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CurriculumLanguageLanguageID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Skillset")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.HasKey("SkillID");

                    b.HasIndex("CurriculumID");

                    b.HasIndex("CurriculumLanguageLanguageID");

                    b.ToTable("Skill");
                });

            modelBuilder.Entity("Model.Poco.SocialLink", b =>
                {
                    b.Property<Guid>("SocialLinkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CurriculumID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CurriculumLanguageLanguageID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("SocialPlatform")
                        .HasColumnType("int");

                    b.HasKey("SocialLinkID");

                    b.HasIndex("CurriculumID");

                    b.HasIndex("CurriculumLanguageLanguageID");

                    b.ToTable("SocialLink");
                });

            modelBuilder.Entity("Model.Poco.Vfile", b =>
                {
                    b.Property<Guid>("VfileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("VfileID");

                    b.ToTable("Vfile");
                });

            modelBuilder.Entity("Model.Poco.About", b =>
                {
                    b.HasOne("Model.Poco.Curriculum", null)
                        .WithMany("Abouts")
                        .HasForeignKey("CurriculumID");

                    b.HasOne("Model.Poco.Language", "CurriculumLanguage")
                        .WithMany()
                        .HasForeignKey("CurriculumLanguageLanguageID");

                    b.HasOne("Model.Poco.Vfile", "Vfile")
                        .WithMany()
                        .HasForeignKey("VfileID");
                });

            modelBuilder.Entity("Model.Poco.Abroad", b =>
                {
                    b.HasOne("Model.Poco.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Poco.Curriculum", null)
                        .WithMany("Abroads")
                        .HasForeignKey("CurriculumID");

                    b.HasOne("Model.Poco.Language", "CurriculumLanguage")
                        .WithMany()
                        .HasForeignKey("CurriculumLanguageLanguageID");
                });

            modelBuilder.Entity("Model.Poco.Award", b =>
                {
                    b.HasOne("Model.Poco.Curriculum", null)
                        .WithMany("Awards")
                        .HasForeignKey("CurriculumID");

                    b.HasOne("Model.Poco.Language", "CurriculumLanguage")
                        .WithMany()
                        .HasForeignKey("CurriculumLanguageLanguageID");
                });

            modelBuilder.Entity("Model.Poco.Certificate", b =>
                {
                    b.HasOne("Model.Poco.Curriculum", null)
                        .WithMany("Certificates")
                        .HasForeignKey("CurriculumID");

                    b.HasOne("Model.Poco.Language", "CurriculumLanguage")
                        .WithMany()
                        .HasForeignKey("CurriculumLanguageLanguageID");
                });

            modelBuilder.Entity("Model.Poco.Child", b =>
                {
                    b.HasOne("Model.Poco.PersonalDetail", null)
                        .WithMany("Children")
                        .HasForeignKey("PersonalDetailID");
                });

            modelBuilder.Entity("Model.Poco.Course", b =>
                {
                    b.HasOne("Model.Poco.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Poco.Curriculum", null)
                        .WithMany("Courses")
                        .HasForeignKey("CurriculumID");

                    b.HasOne("Model.Poco.Language", "CurriculumLanguage")
                        .WithMany()
                        .HasForeignKey("CurriculumLanguageLanguageID");
                });

            modelBuilder.Entity("Model.Poco.Curriculum", b =>
                {
                    b.HasOne("Model.Poco.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageID");
                });

            modelBuilder.Entity("Model.Poco.CurriculumLanguage", b =>
                {
                    b.HasOne("Model.Poco.Curriculum", "Curriculum")
                        .WithMany("CurriculumLanguages")
                        .HasForeignKey("CurriculumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Poco.Language", "Language")
                        .WithMany("CurriculumLanguages")
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Poco.Education", b =>
                {
                    b.HasOne("Model.Poco.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Poco.Curriculum", null)
                        .WithMany("Educations")
                        .HasForeignKey("CurriculumID");

                    b.HasOne("Model.Poco.Language", "CurriculumLanguage")
                        .WithMany()
                        .HasForeignKey("CurriculumLanguageLanguageID");
                });

            modelBuilder.Entity("Model.Poco.Experience", b =>
                {
                    b.HasOne("Model.Poco.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Poco.Curriculum", null)
                        .WithMany("Experiences")
                        .HasForeignKey("CurriculumID");

                    b.HasOne("Model.Poco.Language", "CurriculumLanguage")
                        .WithMany()
                        .HasForeignKey("CurriculumLanguageLanguageID");

                    b.HasOne("Model.Poco.HierarchyLevel", "HierarchyLevel")
                        .WithMany()
                        .HasForeignKey("HierarchyLevelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Poco.Industry", "Industry")
                        .WithMany()
                        .HasForeignKey("IndustryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Poco.Interest", b =>
                {
                    b.HasOne("Model.Poco.Curriculum", null)
                        .WithMany("Interests")
                        .HasForeignKey("CurriculumID");

                    b.HasOne("Model.Poco.Language", "CurriculumLanguage")
                        .WithMany()
                        .HasForeignKey("CurriculumLanguageLanguageID");
                });

            modelBuilder.Entity("Model.Poco.LanguageSkill", b =>
                {
                    b.HasOne("Model.Poco.Curriculum", null)
                        .WithMany("LanguageSkills")
                        .HasForeignKey("CurriculumID");

                    b.HasOne("Model.Poco.Language", "CurriculumLanguage")
                        .WithMany()
                        .HasForeignKey("CurriculumLanguageLanguageID");

                    b.HasOne("Model.Poco.Language", "SpokenLanguage")
                        .WithMany()
                        .HasForeignKey("SpokenLanguageID");
                });

            modelBuilder.Entity("Model.Poco.PersonCountry", b =>
                {
                    b.HasOne("Model.Poco.Country", "Country")
                        .WithMany("PersonCountries")
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Poco.PersonalDetail", "PersonalDetail")
                        .WithMany("PersonCountries")
                        .HasForeignKey("PersonalDetailID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Poco.PersonalDetail", b =>
                {
                    b.HasOne("Model.Poco.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryID");

                    b.HasOne("Model.Poco.Curriculum", null)
                        .WithMany("PersonalDetails")
                        .HasForeignKey("CurriculumID");

                    b.HasOne("Model.Poco.Language", "CurriculumLanguage")
                        .WithMany()
                        .HasForeignKey("CurriculumLanguageLanguageID");

                    b.HasOne("Model.Poco.MaritalStatus", "MaritalStatus")
                        .WithMany()
                        .HasForeignKey("MaritalStatusID");

                    b.HasOne("Model.Poco.Language", "SpokenLanguage")
                        .WithMany()
                        .HasForeignKey("SpokenLanguageID");
                });

            modelBuilder.Entity("Model.Poco.Publication", b =>
                {
                    b.HasOne("Model.Poco.Curriculum", "Curriculum")
                        .WithMany("Publications")
                        .HasForeignKey("CurriculumID");

                    b.HasOne("Model.Poco.Language", "CurriculumLanguage")
                        .WithMany()
                        .HasForeignKey("CurriculumLanguageLanguageID");
                });

            modelBuilder.Entity("Model.Poco.Reference", b =>
                {
                    b.HasOne("Model.Poco.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryID");

                    b.HasOne("Model.Poco.Curriculum", null)
                        .WithMany("References")
                        .HasForeignKey("CurriculumID");

                    b.HasOne("Model.Poco.Language", "CurriculumLanguage")
                        .WithMany()
                        .HasForeignKey("CurriculumLanguageLanguageID");
                });

            modelBuilder.Entity("Model.Poco.Skill", b =>
                {
                    b.HasOne("Model.Poco.Curriculum", null)
                        .WithMany("Skills")
                        .HasForeignKey("CurriculumID");

                    b.HasOne("Model.Poco.Language", "CurriculumLanguage")
                        .WithMany()
                        .HasForeignKey("CurriculumLanguageLanguageID");
                });

            modelBuilder.Entity("Model.Poco.SocialLink", b =>
                {
                    b.HasOne("Model.Poco.Curriculum", null)
                        .WithMany("SocialLinks")
                        .HasForeignKey("CurriculumID");

                    b.HasOne("Model.Poco.Language", "CurriculumLanguage")
                        .WithMany()
                        .HasForeignKey("CurriculumLanguageLanguageID");
                });
#pragma warning restore 612, 618
        }
    }
}
